server:
  port: 8201
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  application:
    name: microservicecloud-config-client
  profiles:
    active: dev
